resources:
  - name: Nginx_app_4
    type: Image
    configuration:
      registry: MyArtifactory
      sourceRepository: local-docker-repo
      imageName: liav_sql
      imageTag: latest
      autoPull: true
      
pipelines:
  - name: pipelines_appimage_2
    steps:
      - name: step_Image_1
        type: Bash
        configuration:
          nodePool: ubuntu_new
          inputResources:
            - name: Nginx_app_4
        execution:
          onExecute:
            - ls
            - pwd
            - echo "liav ha gever"