resources:
  - name: webinfra
    type: Image
    configuration:
      registry: MyArtifactory
      sourceRepository: liav-local-repo
      imageName: webinfra
      imageTag: latest
      autoPull: true
      
pipelines:
  - name: pipelines_appimage
    steps:
      - name: step_Image_1
        type: Bash
        configuration:
          nodePool: ubuntu
          inputResources:
            - name: webinfra
          integrations:
            - name: MyArtifactory
        execution:
          onExecute:
            - ls
            - pwd
            - echo "aaaaaa"