resources:
  - name: NewTest
    type: Image
    configuration:
      registry: MyDockerRepo
      sourceRepository: liav-local-repo
      imageName: liavacademy.jfrogdev.org/liav-local-repo/webinfra
      imageTag: latest
      autoPull: true
      
pipelines:
  - name: Test_2
    steps:
      - name: step_Image_1
        type: Bash
        configuration:
          nodePool: ubuntu
          inputResources:
            - name: NewTest
          integrations:
            - name: MyDockerRepo
        execution:
          onExecute:
            - ls
            - pwd
            - echo "aaaaaa"

  - name: webinfra_build
    type: DockerBuild
    configuration:
      dockerFileLocation: .
      dockerFileName: Dockerfile
      dockerImageName: liavacademy.jfrogdev.org/liav-local-repo/webinfra_dev
      dockerImageTag: ${run_number}
      integrations:
        - name: MyDockerRepo
