resources:
  - name: liavs
    type: Image
    configuration:
      registry: MyDockerRepo
      sourceRepository: liav-local-repo
      imageName: webinfra
      imageTag: latest
      autoPull: true
      
pipelines:
  - name: Test_2
    steps:
      - name: step_Image_1
        type: Bash
        configuration:
          nodePool: ubuntu
          inputResources:
            - name: liavs
          integrations:
            - name: MyDockerRepo
        execution:
          onExecute:
            - ls
            - pwd
            - echo "aaaaaa"