# resources:
  # - name: Nginx_app
  #   type: Image
  #   Configuration:
  #     registry: MyArtifactory
  #     sourceRepository: local-docker-repo
  #     imageName: appimage
  #     imageTag: latest


pipelines:
  - name: pipelines_appimage
    steps:
      - name: step_Image_1
        type: Bash
        configuration:
          nodePool: ubuntu
          # inputResources:
          #   - name: Nginx_app
        execution:
          onExecute:
            - ls
            - pwd
            - ifconfig
            - echo "liav ha gever"